/** Autogenerated template. */

const runSolution = (input: string[]): any => {
  const days: number[] = Array.from({ length: 9 }).map((x) => 0);
  const fishes: number[] = input[0].split(",").map(Number);

  const numDays = 365;

  for (const fish of fishes) {
    days[fish] += 1;
  }

  for (let i = 0; i < numDays; i++) {
    const today = i % days.length;
    days[(today + 7) % days.length] += days[today];
  }

  return days.reduce((accumulator, current) => accumulator + current, 0);
};

export default runSolution;
