/** Autogenerated template. */

const targetSignalLength = [2, 3, 4, 7];
const selectSignalsWithUniqueSegments = (listOfSignals: string[]) =>
  listOfSignals.filter((signal) =>
    targetSignalLength.includes(signal.trim().length)
  );

const sortSignalValues = (listOfSignals: string[]): string[] =>
  listOfSignals.map((signal) =>
    [...signal].sort((a, b) => a.localeCompare(b)).join("")
  );

const runSolution = (input: string[]): any => {
  /** Solution goes here */
  const outputDigits: string[] = input
    .map((line) => line.split("|")[1])
    .map((line) => line.split(" "))
    .map(selectSignalsWithUniqueSegments)
    .reduce((accumulator, current) => accumulator.concat(current), []);

  return outputDigits.length;
};

export default runSolution;
