/** Autogenerated template. */

import getParsedInput from "../../lib/inputParser";

const CHALLENGE_DIR_NAME = "d4GiantSquid";

const input: string[] = getParsedInput({
  challengeDirName: CHALLENGE_DIR_NAME,
});

export default input;
