/** Autogenerated template. */

import getParsedInput from "../lib/inputParser";
import logger from "../lib/logger";

import runSolutionForChallenge1 from "./challenge1";
import runSolutionForChallenge2 from "./challenge2";

const CHALLENGE_DIR_NAME = "d13TransparentOrigami";

const input: string[] = getParsedInput({
  challengeDirName: CHALLENGE_DIR_NAME,
});

const inputTransformer = (input: string[]): any => {
  const dotPositions = input.filter((entry) => !entry.startsWith("fold along"));
  const foldInstructions = input
    .filter((entry) => entry.startsWith("fold along"))
    .map((instruction) => instruction.replace("fold along ", ""));
  return { dotPositions, foldInstructions };
};

const challenge1Solution = runSolutionForChallenge1(inputTransformer(input));
const challenge2Solution = runSolutionForChallenge2(inputTransformer(input));

logger.logSolution("Solution to challenge 1", challenge1Solution);
logger.logSolution("Solution to challenge 2", challenge2Solution);
